# Generated by Django 5.1.3 on 2024-12-09 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="type_dish",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_app.dishtype",
            ),
        ),
    ]
